# Generated by Django 3.1.3 on 2020-12-13 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_wsp', models.URLField(max_length=500, verbose_name='Link de WhatsApp')),
                ('url_zoom', models.URLField(max_length=500, verbose_name='Link de Zoom')),
                ('url_fb_messenger', models.URLField(max_length=500, verbose_name='Link de Messenger de Facebook')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
    ]
