# Generated by Django 3.1.3 on 2020-12-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'Diseñador', 'verbose_name_plural': 'Diseñadores'},
        ),
    ]
