# Generated by Django 3.1.3 on 2020-12-14 13:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0002_auto_20201213_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudImpresionObjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita:')),
                ('object_print', models.CharField(max_length=1000, verbose_name='Objeto a Imprimir:')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación:')),
                ('descripcion_complementaria', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Complementaria:')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.design')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Impresión Objeto',
                'verbose_name_plural': 'Solicitudes Impresión Objeto',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita:')),
                ('formato_img', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('pdf', 'pdf'), ('jpeg', 'jpeg'), ('svg', 'svg'), ('illustrator (ai)', 'illustrator (ai)'), ('photoshop (psd)', 'photoshop (psd)')], max_length=50, verbose_name='Formato de la Imagen:')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación:')),
                ('descripcion_complementaria', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Complementaria:')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.design')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Diseño',
                'verbose_name_plural': 'Solicitudes Diseños',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDesignImpresionPapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita:')),
                ('size', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('Carta', 'Carta'), ('Oficio', 'Oficio')], max_length=50, verbose_name='Tamaño del papel:')),
                ('type_print', models.CharField(choices=[('Offset', 'Offset'), ('Digital', 'Digital')], max_length=50, verbose_name='Tipo de impresión:')),
                ('type_paper', models.CharField(choices=[('Couché', 'Couché'), ('Creativo', 'Creativo'), ('Offset', 'Offset'), ('Reciclado', 'Reciclado'), ('Autoadhesivo', 'Autoadhesivo')], max_length=50, verbose_name='Tipo de papel:')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación:')),
                ('descripcion_complementaria', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Complementaria:')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.design')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Diseño + Impresión Papel',
                'verbose_name_plural': 'Solicitudes Diseño + Impresión Papel',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDesignImpresionObjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita:')),
                ('object_print', models.CharField(max_length=1000, verbose_name='Objeto a Imprimir:')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación:')),
                ('descripcion_complementaria', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Complementaria:')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.design')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Diseño + Impresión Objeto',
                'verbose_name_plural': 'Solicitudes Diseño + Impresión Objeto',
            },
        ),
    ]
