# Generated by Django 3.1.3 on 2020-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha Cita')),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL-Large')], max_length=50, verbose_name='Talla')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación')),
            ],
            options={
                'verbose_name': 'DatosCita',
                'verbose_name_plural': 'DatosCitas',
            },
        ),
    ]
