# Generated by Django 3.1.3 on 2020-12-06 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscita',
            name='descripcion_complementaria',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
