# Generated by Django 3.1.3 on 2020-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddesignimpresionobjeto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicituddesignimpresionobjeto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preio'),
        ),
        migrations.AddField(
            model_name='solicituddesignimpresionpapel',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicituddesignimpresionpapel',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preio'),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preio'),
        ),
        migrations.AddField(
            model_name='solicitudimpresionobjeto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudimpresionobjeto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preio'),
        ),
    ]
