# Generated by Django 3.1.3 on 2020-12-13 16:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0004_auto_20201206_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita:')),
                ('formato_img', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('pdf', 'pdf'), ('jpeg', 'jpeg'), ('svg', 'svg'), ('illustrator(ai)', 'illustrator(ai)'), ('photoshop(psd)', 'photoshop(psd)')], max_length=50, verbose_name='Formato de la Imagen:')),
                ('medio_comunicacion', models.CharField(choices=[('Zoom', 'Zoom'), ('WhatsApp', 'WhatsApp'), ('FB-messenger', 'FB-messenger')], max_length=50, verbose_name='Medio de Comunicación:')),
                ('descripcion_complementaria', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción Complementaria:')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SolicitudDiseño',
                'verbose_name_plural': 'SolicitudDiseños',
            },
        ),
    ]
