# Generated by Django 3.1.3 on 2020-12-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20201213_1538'),
        ('producto', '0005_solicituddiseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddiseno',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.design'),
        ),
    ]
