# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201124_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codregistro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
