# Generated by Django 3.1.3 on 2020-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20201206_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='monto_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
