# Generated by Django 3.1.3 on 2020-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201206_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
