# Generated by Django 3.1.3 on 2020-12-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuarios_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
